### ISSUE TITLE
Its automatic record bot ?

### ISSUE THREAD

**Issue by Takanashi-Rikka1** [MichaelKheel/WRBot#1]
Hello , have question its a automatic bot ?
i mean when player did 1st in the server
Bot created and u can see it in the server.

Or its manually? and need record it and send to owner of the server.

**Comment by MichaelKheel** [comment]
> Hello , have question its a automatic bot ?
> i mean when player did 1st in the server
> Bot created and u can see it in the server.
> 
> Or its manually? and need record it and send to owner of the server.

No, this is a world record bot. The description contains information. What you want is in the plugin  [ProKreedz](https://github.com/MichaelKheel/ProKreedz)

**Comment by Takanashi-Rikka1** [comment]
> > Hello , have question its a automatic bot ?
> > i mean when player did 1st in the server
> > Bot created and u can see it in the server.
> > Or its manually? and need record it and send to owner of the server.
> 
> No, this is a world record bot. The description contains information. What you want is in the plugin [ProKreedz](https://github.com/MichaelKheel/ProKreedz)

Oh i will check it but im not success compile it..
